### PR TITLE
Revert "Improve water rendering"

### LINKED ISSUE #156: fix broken rendering
also would be good to have something that checks this automatically somehow (https://prismarine.js.org/prismarine-viewer/ pretty clearly show the existence of the pb)

### PR DESCRIPTION
**Pull request by rom1504**
This reverts commit e8f439f603fa60e4a3e3bbc6c99195b5b7fe35e5.

Trying to fix #156

### CODE REVIEW

**Comment by rom1504** [comment]
can confirm this fixes looking at artifact there https://github.com/PrismarineJS/prismarine-viewer/actions/runs/630280650

what do you think @Karang ? let's merge and investigate later ?

File: viewer/lib/models.js [hunk 1]
```diff
@@ -69,63 +69,47 @@ const elemFaces = {
...
-    }
-  }
-  const cornerHeights = [
-    Math.max(Math.max(heights[0], heights[1]), Math.max(heights[3], heights[4])),
-    Math.max(Math.max(heights[1], heights[2]), Math.max(heights[4], heights[5])),
-    Math.max(Math.max(heights[3], heights[4]), Math.max(heights[6], heights[7])),
-    Math.max(Math.max(heights[4], heights[5]), Math.max(heights[7], heights[8]))
-  ]
+function renderLiquid (world, cursor, texture, type, water, attr) {
+  const blockAbove = world.getBlock(cursor.offset(0, 1, 0))
```
Comment (rom1504) [inline viewer/lib/models.js:73]: this getBlock might be the slow part ?
